name: End-to-End Testes
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v5
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome